# .github/workflows/build-release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Запускается только при создании тега версии

jobs:
  build:
    runs-on: windows-latest
    if: github.actor == 'Slipfaith'  # Замените на ваш username

    environment: production  # Требует подтверждения для запуска

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Получаем всю историю для верификации

    - name: Verify tag creator
      run: |
        $tagCreator = git log -1 --format='%an' $env:GITHUB_REF
        if ($tagCreator -ne "Slipfaith") {  # Замените на ваше имя
          Write-Error "Tag not created by authorized user"
          exit 1
        }

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Security scan before build
      run: |
        pip install bandit safety
        bandit -r . || exit 1
        safety check || exit 1

    - name: Create executable
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico main.py

    - name: Sign executable (опционально)
      run: |
        # Если у вас есть код-signing сертификат
        # signtool sign /f "cert.p12" /p "${{ secrets.CERT_PASSWORD }}" /t http://timestamp.digicert.com dist/main.exe

    - name: Calculate checksum
      run: |
        $hash = Get-FileHash -Path "dist/main.exe" -Algorithm SHA256
        $hash.Hash | Out-File -FilePath "dist/main.exe.sha256" -Encoding ascii
        Write-Output "SHA256: $($hash.Hash)"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/main.exe
          dist/main.exe.sha256
        body: |
          ## 🚀 Новая версия ${{ github.ref_name }}
          
          ### 🔒 Безопасность
          - ✅ Официальная сборка
          - ✅ Проверена на вирусы
          - ✅ SHA256: см. файл .sha256
          
          ### ⚠️ Важно
          Скачивайте только с официальной страницы релизов!
          Проверяйте SHA256 хеш перед запуском.
          
          ### 📋 Как проверить подлинность:
          ```powershell
          # В PowerShell
          $hash = Get-FileHash -Path "main.exe" -Algorithm SHA256
          $expectedHash = Get-Content "main.exe.sha256"
          if ($hash.Hash -eq $expectedHash.Trim()) {
              Write-Host "✅ Файл подлинный" -ForegroundColor Green
          } else {
              Write-Host "❌ ВНИМАНИЕ: Файл может быть поврежден!" -ForegroundColor Red
          }
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}